version: '3.1'

services:
  pastehex-db:
    container_name: pastehex-db
    image: postgres:11
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTRGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432